- continuing with the testsuite - starting with an option to specify the dlv-executable at configure-time (works, but it doesn't look nice to me)

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -7,8 +7,8 @@ echo "aclocal..."
 aclocal -I m4 \
     || { echo "aclocal failed"; exit 1; }
 echo "autoheader..."
-#autoheader --warnings=all \
-#    || { echo "autoheader failed"; exit 1; }
+autoheader --warnings=all \
+    || { echo "autoheader failed"; exit 1; }
 echo "automake..."
 automake --warnings=all --warnings=no-syntax --foreign --add-missing \
     || { echo "automake failed"; exit 1; }
